### ISSUE TITLE
[FEATURE] Contract address Problem

### ISSUE THREAD

**Issue by ChunHuCui** [Anchor-Protocol/money-market-contracts#55] opened 2021-11-15 05:42 UTC
1. I cloned the money market contracts and found one problem. (cloned contracts address: terra15dzu8daqh5shdda6w79vl4hkw73fzrhzfhr7fe)
  Once I deposit the UST to my own cloned money market contracts, then this contract deposits 100 Token from terra1yemu0kt0sgkpa8gghr8paqxdeup0ucr430gph0.
  https://finder.terra.money/testnet/address/terra1yemu0kt0sgkpa8gghr8paqxdeup0ucr430gph0
![image](https://user-images.githubusercontent.com/68866354/141728598-55faafdf-caaa-465f-9e49-6982323652b5.png)

I'd like to know this contract(terra1yemu0kt0sgkpa8gghr8paqxdeup0ucr430gph0) is from where?

the above image is from the anchor money market contract.
![image](https://user-images.githubusercontent.com/68866354/141728913-42b19ccb-0a27-4764-beb7-41e811e112d6.png)

- on the original money market contract:
  once I deposit 100USD, mint 87aUST.
- on the cloned money market contract:
  once I deposit 100USD, mint 100Token of terra1yemu0kt0sgkpa8gghr8paqxdeup0ucr430gph0.
 
my wallet address: terra14g430dz4gnv3g4w449fadcj22cvapcj860nsz2
my cloned money market contract address: terra15dzu8daqh5shdda6w79vl4hkw73fzrhzfhr7fe

Thank you.

**Comment by ChunHuCui** [comment] 2021-11-16 05:50
wow, thank you for your reply.
Then could you possibly let me know how to create terra1yemu0kt0sgkpa8gghr8paqxdeup0ucr430gph0 token.
actually, I did not create the above token.
thank you.

**Comment by ChunHuCui** [comment] 2021-11-16 05:54
and could you possibly let me know how to moderate the exchange rate from my own token and UST?
Thank you in advance.

**Comment by petes-fan-club** [comment] 2021-11-16 14:07
discord is a better place to ask questions - https://discord.gg/68dNrWS5DZ
if this is not a bug, then please close the issue

**Closed** 2021-11-17 09:19 UTC
Labels: enhancement
